Sprint 1/step 2
vanobl/s1_p1 pull request #1
Opened 2023-08-05 10:58 UTC by vanobl

Сдача работы

2023-08-05 11:59 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Есть модальные окна;
- Данные получают с сервера;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/nEJresSW_-9g-g> - Нужно исправить ошибки в консоли.

- <https://disk.yandex.com/i/DsQTtbA1Y46dEw> - Нужно поправить внешний вид булок. А также, по макету у булок должна быть приписка `(верх)` и `(низ)`.

- <https://disk.yandex.com/i/aqk3O6JCofAXNQ> - 1-ая ссылка должны быть активной (белый цвет у иконки и текста);

- В компоненте App-header требуется поправить семантику, переделать div в ссылки.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь <https://learn.javascript.ru/coding-style>. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (<https://prettier.io/>)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/App/App.jsx
> +    return ReactDOM.createPortal(
**Надо исправить:**

`ReactDOM.createPortal` - должен быть в компоненте modal.

Использоваться компонент modal нужно следующим образом.

```js
{ isOpen && <Modal onClose={handleCloseIngredientDetails} header="Детали ингредиента">
   <IngredientDetails data={data} />
<Modal>}

// и

{ isOpen && <Modal onClose={handleCloseOrderDetails}>
   <OrderDetails />
<Modal>}
```

Для каждого модального окна должны быть свои обработчики.

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/App/App.jsx
> +        <ModalOverlay offModal={offModal} />
**Надо исправить:**

`ModalOverlay` - должен быть в компоненте `modal`

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/App/App.jsx
> +          <ModalHeader headerText="" offModal={offModal} />
**Надо исправить:**

`ModalHeader` - Должен быть в компоненте modal

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/App/App.jsx
> +  }
**Надо исправить:**

Добавьте проверку ответа сервера - res.ok:

Например:

```js
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответит не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```js
const checkResponse = res => {
  return res.ok ? res.json() : res.json().then(err => Promise.reject(err));
};
```

`fetch(someUrl).then(checkResponse)`

<!--  -->

**Надо исправить:**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```js
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}
```

и разместить их в отдельном файле `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/App/App.jsx
> +      {modalActive && modal}
**Надо исправить:**

используйте модальные окна в тех компонентах где они используются (`BurgerConstructor` и `BurgerIngridients`).
Использование модальных окон в app, немного вредит производительности приложения, т.к. изменения стейта тут перерисовывает всё приложение.

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/AppHeader/AppHeaderButton.jsx
> +};
**Надо исправить:**

- Не стоит переусложнять логику в данном компоненте.
- Делать ховер эффект нужно через css.
- Используйте проп `children` чтобы передавать нужную иконку и текст https://react.dev/reference/react/Children.
- Уберите пропс `last`, - он тут избыточен, используйте псевдоселекторы в css
- Нужно описать PropTypes

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    const [total, setTotal] = useState(0);
**Надо исправить:**

не стоит считать цену через useState.

Используйте useMemo

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                    <Button htmlType="button" type="primary" size="large" extraClass="ml-10" onClick={() => {props.onModal('order', getNumberOrder())}}>Оформить заказ</Button>
**Надо исправить:**

создайте отдельный обработчик для onClick, и пишите логику там.

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +const BurgerConstructor = (props) => {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerElement.jsx
> +const BurgerElement = (props) => {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/BurgerConstructor/SectionBurger.jsx
> +    let sauce = getSauce();
**Надо исправить:**

Лучше изначально разделить булку и ингредиенты:

```js
const { bun, ingredients } = useMemo(() => {
  return {
    bun: data.find(item => item.type === 'bun'),
    ingredients: data.filter(item => item.type !== 'bun'),
  };
}, [data]);
```

Что-то вы намудрили тут, всё намного проще)
Не нужно сейчас пытаться делать рандом ингредиентов. Цель данного спринта научиться работать с запросами, модальными окнами и jsx.

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/BurgerConstructor/SectionBurger.jsx
> +                text={bun.name}
**Надо исправить:**

Здесь и далее.

По макету у булок должна быть приписка `(верх)` и `(низ)`.

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +                />
**Надо исправить**

Лучше в компоненте делать filter по массиву, а потом отображать полученный массив.

Например:

```js
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
const sauces = useMemo(data.filter((item) => item.type === 'sauce'), [data]);

return (
   ....................
   {buns.map(....................)}
   ..................
)
```

А не располагать фильтрацию в нижестоящих компонентах

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +const BurgerIngredients = (props) => {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/BurgerConstructor/SectionBurger.jsx
> +const SectionBurger = React.memo((props) => {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/BurgerIngredients/IngredientsList.jsx
> +const IngredientsList = (props) => {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/BurgerIngredients/IngredientsList.jsx
> +        </div>
**Надо исправить:**

добавьте сюда пропс title, и удалите компонент NameSection, он избыточен.

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/BurgerIngredients/ItemIngredient.jsx
> +const ItemIngredient = (props) => {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/BurgerIngredients/NameSection.jsx
> +const NameSection = (props) => {
**Надо исправить:**

в данном случае не стоит выносить в отдельный компонент просто текст.

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/Modal/Modal.jsx
> +const Modal = (props) => {
**Надо исправить:**

- Для этого компонента так же нужно описать PropTypes.

**Надо исправить:**

Обработчик закрытия попапа должен добавляться при открытии попапа и удаляться при закрытии. Сейчас обработчик не будет удаляться при закрытии попапа т.к. из хука useEffect нужно возвращать колбэк отписки. Должно быть примерно так:

```js
   useEffect(() => {
      const handleESCclose = () => {............} //обработчик события
      document.addEventListener("keydown", handleESCclose); //навешиваем обработчик
	  
	  //возвращаем колбэк отписки, который  будет вызван при размонтировании компонента
      return () => document.removeEventListener("keydown", handleESCclose)                                                                                               
   }, [onClose])
```

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/Modal/ModalHeader.jsx
> +}
**Надо исправить:**

Нужно удалить компонент и перенести содержимое в Modal. Также  стоит переименовать пропс `offModal` в `onClose`

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/Modal/ModalOverlay.jsx
> +const ModalOverlay = (props) => {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/Modal/NutritionItem.jsx
> +const NutritionItem = (props) => {
**Надо исправить:**

В данном случае не стоит разделять верстку окна Детали ингредиента на компоненты. Пишите всё в IngredientDetails

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/Modal/NutritionsList.jsx
> +const NutritionsList = (props) => {
**Надо исправить:**

В данном случае не стоит разделять верстку окна Детали ингредиента на компоненты. Пишите всё в IngredientDetails

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/Modal/SpaceCheckIcon.jsx
> +}
Надо исправить:

В данном случае не стоит разделять верстку окна Детали заказа на компоненты. Пишите всё в OrderDetails

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/App/App.jsx
> +  function createModalOrder(modalBody) {
**Надо исправить:**

вам нужно создать отдельный компонент OrderDetails, где будет находиться контент для модального окна.

2023-08-05 11:59 UTC, ArslanMustafin commented on src/components/App/App.jsx
> +  function createModalIngredient(modalBody) {
**Надо исправить:**

вам нужно создать отдельный компонент IngredientDetails, где будет находиться контент для модального окна.

2023-08-05 16:31 UTC, vanobl commented on src/components/App/App.jsx
> +    return ReactDOM.createPortal(
А для чего делать для каждого модального окна свой обработчик закрытия? Смысл то один и тот же.

2023-08-05 18:46 UTC, ArslanMustafin commented on src/components/App/App.jsx
> +    return ReactDOM.createPortal(
Для того чтобы можно было расширять функционал в дальнейшем, а не плодить условие под каждое окно. А также функция должна делать что-то 1.

2023-08-05 18:57 UTC, vanobl commented on src/components/AppHeader/AppHeaderButton.jsx
> +};
Подскажите, пожалуйста, каким образом через css hover можно поменять в <BurgerIcon type="primary" /> свойство  type ?

2023-08-05 18:58 UTC, vanobl commented on src/components/AppHeader/AppHeaderButton.jsx
> +};
Подскажите, пожалуйста, каким образом через css hover можно поменять в `<BurgerIcon type="primary" />` свойство type ?

2023-08-05 19:00 UTC, vanobl commented on src/components/BurgerConstructor/SectionBurger.jsx
> +    let sauce = getSauce();
Может тогда это и исправлять не нужно?

2023-08-05 19:20 UTC, vanobl commented on src/components/App/App.jsx
> +    return ReactDOM.createPortal(
Нет я про **handleCloseIngredientDetails** и **handleCloseOrderDetails** они ведь явно делают одно и тоже. Так же вопрос про

2023-08-06 13:40 UTC, vanobl commented on src/components/App/App.jsx
> +    return ReactDOM.createPortal(
исправлено

2023-08-06 13:54 UTC, vanobl commented on src/components/App/App.jsx
> +        <ModalOverlay offModal={offModal} />
исправлено

2023-08-06 13:55 UTC, vanobl commented on src/components/App/App.jsx
> +          <ModalHeader headerText="" offModal={offModal} />
исправлено

2023-08-06 13:55 UTC, vanobl commented on src/components/App/App.jsx
> +      {modalActive && modal}
исправлено

2023-08-06 13:55 UTC, vanobl commented on src/components/AppHeader/AppHeaderButton.jsx
> +};
Я так и не понял как изменить свойство через css. И ответа от вас не дождался.

2023-08-06 13:59 UTC, vanobl commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                    <Button htmlType="button" type="primary" size="large" extraClass="ml-10" onClick={() => {props.onModal('order', getNumberOrder())}}>Оформить заказ</Button>
исправлено

2023-08-06 13:59 UTC, vanobl commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +const BurgerConstructor = (props) => {
исправлено

2023-08-06 13:59 UTC, vanobl commented on src/components/BurgerConstructor/BurgerElement.jsx
> +const BurgerElement = (props) => {
исправлено

2023-08-06 14:00 UTC, vanobl commented on src/components/BurgerConstructor/SectionBurger.jsx
> +                text={bun.name}
исправлено

2023-08-06 14:02 UTC, vanobl commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +const BurgerIngredients = (props) => {
исправлено

2023-08-06 14:02 UTC, vanobl commented on src/components/BurgerConstructor/SectionBurger.jsx
> +const SectionBurger = React.memo((props) => {
исправлено

2023-08-06 14:02 UTC, vanobl commented on src/components/BurgerIngredients/IngredientsList.jsx
> +const IngredientsList = (props) => {
исправлено

2023-08-06 14:09 UTC, vanobl commented on src/components/BurgerIngredients/ItemIngredient.jsx
> +const ItemIngredient = (props) => {
исправлено

2023-08-06 14:11 UTC, vanobl commented on src/components/Modal/ModalOverlay.jsx
> +const ModalOverlay = (props) => {
исправлено

2023-08-06 14:12 UTC, vanobl commented on src/components/App/App.jsx
> +  function createModalOrder(modalBody) {
исправлено

2023-08-06 14:13 UTC, vanobl commented on src/components/App/App.jsx
> +  function createModalIngredient(modalBody) {
исправлено

2023-08-06 14:24 UTC, vanobl commented on src/components/App/App.jsx
> +  }
исправлено без переноса в отдельный файл

2023-08-06 20:55 UTC, vanobl commented on src/components/BurgerIngredients/NameSection.jsx
> +const NameSection = (props) => {
исправлено

2023-08-06 21:09 UTC, vanobl commented on src/components/Modal/Modal.jsx
> +const Modal = (props) => {
исправлено

2023-08-06 21:13 UTC, vanobl commented on src/components/Modal/ModalHeader.jsx
> +}
исправлено

2023-08-06 21:17 UTC, vanobl commented on src/components/Modal/NutritionsList.jsx
> +const NutritionsList = (props) => {
исправлено

2023-08-06 21:22 UTC, vanobl commented on src/components/Modal/NutritionItem.jsx
> +const NutritionItem = (props) => {
исправлено

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +      {props.ingridients && <SectionBurger ingridients={props.ingridients} setTotal={setTotal} />}
**Надо исправить:**

проверка избыточна, т.к. вы в компоненте app проверяете уже этот пропс.

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/BurgerConstructor/SectionBurger.jsx
> +        key={bunIdTop}
**Надо исправить:**

тут не нужно указывать ключ.

https://ru.react.js.org/docs/lists-and-keys.html

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/BurgerConstructor/SectionBurger.jsx
> +  props.setTotal(total);
**Надо исправить:**

сейчас не стоит делать лишний функционал. В 3 спринте у вас появится редакс, и вы будете считать цену, реализовывать DnD через него и т.д. А сейчас этот фукнциона немного лишний, и не очень хорошо влияет на код. 

В данном спринте (в данном компоненте) просто разделите булку, ингредиенты и выведите их. 
Это можно сделать следующим образом.

```js
const { bun, ingredients } = useMemo(() => {
  return {
    bun: data.find(item => item.type === 'bun'),
    ingredients: data.filter(item => item.type !== 'bun'),
  };
}, [data]);
```

И в этом компоненте не нужны никакие проверки в jsx.

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/BurgerConstructor/SectionBurger.jsx
> +  ingridients: PropTypes.object,
**Надо исправить:**

Требуется полное описание структуры ингредиента, а не propTypes.object.
А также необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/BurgerConstructor/SectionBurger.jsx
> +      <BurgerElement {...sauce} />
**Надо исправить:**

ингредиент лучше передавать в качестве обьекта. А если вы хотите выбрать какие-то определнные свойства, то их нужно явно указать, а не делать это через Spread-оператор

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerElement.jsx
> +};
**Надо исправить:**

описаны не все поля ингредиента.

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/App/App.jsx
> +      />}
**Можно лучше:**

Проверки лучше объединить.

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  ingridients: PropTypes.object
**Надо исправить:**

Требуется полное описание структуры ингредиента, а не propTypes.object.
А также необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  ingridients: PropTypes.object
**Надо исправить:**

Требуется полное описание структуры ингредиента, а не propTypes.object.
А также необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/BurgerIngredients/IngredientsList.jsx
> +  ingridients: PropTypes.object,
**Надо исправить:**

Требуется полное описание структуры ингредиента, а не propTypes.object.
А также необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/BurgerIngredients/IngredientsList.jsx
> +      {props.ingridients && props.ingridients.map(info => <ItemIngredient
**Надо исправить:**

проверка тут избыточна, она уже есть в app

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/BurgerIngredients/ItemIngredient.jsx
> +        <p className="text text_type_digits-default">{props.info.price}</p>&nbsp;
**надо исправить:**

лучше использовать стили для добавления растояния между элементами. `gap`

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/BurgerIngredients/ItemIngredient.jsx
> +  info: PropTypes.object
**Надо исправить:**

Требуется полное описание структуры ингредиента, а не propTypes.object.

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/Modal/IngredientDetails.jsx
> +  ingredient: PropTypes.object
**Надо исправить:**

Требуется полное описание структуры ингредиента, а не propTypes.object.

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/Modal/IngredientDetails.jsx
> +const IngredientDetails = (props) => {
**Можно лучше:**

лучше вынести в отдельную папку как, как вы сделали с остальными компонентами.

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/Modal/Modal.jsx
> +  const escFunction = useCallback((event) => {
**Надо исправить:**

useCallback тут избыточен, занесите просто функцию в useEffect.

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/Modal/Modal.jsx
> +  offModal: PropTypes.func,
**Надо исправить:**

тут .isRequired

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/Modal/ModalOverlay.jsx
> +  offModal: PropTypes.func
**Надо исправить:**

тут .isRequired

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/Modal/ModalOverlay.jsx
> +        {props.children}
**Надо исправить:**

`props.children` - тут не используется, поэтому можно удалить. Не забудьте удалить и из propTypes тоже

2023-08-07 04:12 UTC, ArslanMustafin commented on src/components/App/App.jsx
> +    return ReactDOM.createPortal(
> Нет я про **handleCloseIngredientDetails** и **handleCloseOrderDetails** они ведь явно делают одно и тоже.

Делают может быть и одно и тоже, но для разных вещей. Тут дело в том, что если у вас будет оч много модальных окон, то писать для каждого окна условие закрытие в 1-ой функции оч не оптимально.

2023-08-07 04:15 UTC, ArslanMustafin commented on src/components/Utils/burger-api.js
> +  return fetch("https://norma.nomoreparties.space/api/ingredients").then(
**Надо исправить:**

вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

2023-08-07 04:15 UTC, ArslanMustafin commented on src/components/App/App.jsx
> +  }
Нужно вынести и использовать)

2023-08-07 04:25 UTC, ArslanMustafin commented on src/components/BurgerConstructor/SectionBurger.jsx
> +    let sauce = getSauce();
Нужно, так будет проще подстроить логику для работы с редакс. Допустим {bun, ingredients} (разделение булки и ингредиента) это оптимальная структура для редьюсера конструктора, вам нужно будет только написать редьюсер и экшены, а вся логика уже будет завязана на этой структуре.

2023-08-07 04:30 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец!**

- Большинство замечаний было исправлено;

### **Но есть ещё несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/Hw5OYpUHD0L6Sw> - булки должны оставаться на месте, скролл есть только у ингредиентов.

- <https://disk.yandex.com/i/16S-Z2HqHqvR_g> - Нужно убрать надпись у модального окна заказа.

- Нужно удалить весь закоменченный код, который дублируется в компоненте app. Он у вас в любом случае останется на гитхабе, поэтому не стоит держать такие вещи в проекте. (функция для api-запросов)

- Не исправлены следующие замечания:

  - <https://github.com/vanobl/s1_p1/pull/1#discussion_r1285029844>

    - Если вы что-то не понимаете, то нужно обращаться к наставнику.
    - Иконка это svg, поэтому менять её цвет можно через css свойство fill.
    - Используйте проп children чтобы передавать нужную иконку и текст <https://react.dev/reference/react/Children>.

  - <https://github.com/vanobl/s1_p1/pull/1#discussion_r1285030717>;
  - <https://github.com/vanobl/s1_p1/pull/1#discussion_r1285034837>;

- key нужно указывать только при итерации в списке - <https://ru.react.js.org/docs/lists-and-keys.html>;

2023-08-07 19:43 UTC, vanobl commented on src/components/Utils/burger-api.js
> +  return fetch("https://norma.nomoreparties.space/api/ingredients").then(
исправлено

2023-08-07 19:43 UTC, vanobl commented on src/components/Modal/ModalOverlay.jsx
> +        {props.children}
исправлено

2023-08-07 19:44 UTC, vanobl commented on src/components/Modal/ModalOverlay.jsx
> +  offModal: PropTypes.func
исправлено

2023-08-07 19:44 UTC, vanobl commented on src/components/Modal/Modal.jsx
> +  offModal: PropTypes.func,
исправлено

2023-08-07 19:44 UTC, vanobl commented on src/components/Modal/Modal.jsx
> +  const escFunction = useCallback((event) => {
исправлено

2023-08-08 03:00 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Но есть ещё пару замечаний, которые нужно исправить:**

- Добавьте проверку ответа сервера. Описал в коде как это можно сделать;

- Во многих компонентах дублируется описание PropTypes ингредиента. Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингредиента, а не дублировать.

2023-08-08 03:00 UTC, ArslanMustafin commented on src/components/App/App.jsx
> +  let data = await getIngredients();
**Можно лучше:**

```js
  try {
    const { data } = await getIngredients()
    
    const res = data.data.reduce((acc, curVal) => {
      let type = curVal.type;
      if (!acc[type]) {
        acc[type] = [];
      }
      acc[type].push(curVal);
      return acc;
  }, {});

  } catch (error) {
    // обработка ощибки, если она случится во время выполнения запроса.
  }
```

2023-08-08 03:00 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerElement.jsx
> +};
**Надо исправить:**

во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать

2023-08-08 03:00 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +     <SectionBurger />
**Надо исправить:**

Вы должны использовать данные которые пришли к вам с сервера, а не захардкоженные.

2023-08-08 03:00 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  ).isRequired
**Надо исправить:**

во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать.

Неправильно описаны propTypes. Должно быть так.

```js
BurgerIngredients.propTypes = {
  ingridients: PropTypes.shape({ 
    bun: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired,
    main: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired,
    sauce: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired
  })
}
```

2023-08-08 03:00 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +            ingridients={props.ingridients && props.ingridients.bun}
**Надо исправить:**

Здесь и далее.

Проверка на `props.ingridients` тут избыточно, её можно удалить.

2023-08-08 03:00 UTC, ArslanMustafin commented on src/components/BurgerIngredients/IngredientsList.jsx
> +  ).isRequired,
**Надо исправить:**

во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать

2023-08-08 03:00 UTC, ArslanMustafin commented on src/components/BurgerIngredients/ItemIngredient.jsx
> +  }).isRequired
**Надо исправить:**

во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать

2023-08-08 03:00 UTC, ArslanMustafin commented on src/components/Modal/IngredientDetails.jsx
> +  }.isRequired
**Надо исправить:**

во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать

2023-08-08 03:00 UTC, ArslanMustafin commented on src/components/Modal/SpaceCheckIcon.jsx
> +};
**Можно лучше:**

Не стоит выносить код в отдельный компонент, ради 1 иконки.

2023-08-08 03:00 UTC, ArslanMustafin commented on src/components/Utils/burger-api.js
> +};
**Надо исправить:**

Константы принято записывать в `UPPER_CASE`

**Надо исправить:**

Добавьте проверку ответа сервера - res.ok:

Например:

```js
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответит не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```js
const checkResponse = res => {
  return res.ok ? res.json() : res.json().then(err => Promise.reject(err));
};
```

`fetch(someUrl).then(checkResponse)`

2023-08-08 17:18 UTC, vanobl commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +     <SectionBurger />
согласно чек-листу данное требование есть только для BurgerIngredients, для BurgerConstructor данного требования нет.

2023-08-08 17:45 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +     <SectionBurger />
Данное требование есть в задании - https://disk.yandex.com/i/DDO4Ws67Uz9FIA.

2023-08-08 17:58 UTC, vanobl commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +     <SectionBurger />
В будущем возможно, но на данном этапе нужно просто собрать интерфейс. Да и как их использовать, если мы ещё не прошли темы для данного использования? То, что я сделал в предыдущей редакции, вам не понравилось и вы сказали, что это пока не требуется. В чек-листе данного требования нет, по этому данные просто вшиты в код. Когда пройдём нужные темы, вшитые данные заменятся интрерактивными.

2023-08-08 18:16 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +     <SectionBurger />
как это в будущем, в задание ведь чётко сказано, что нужно использовать данные с сервера, а не захардкоженные.
Вас никто не просит делать функционал какой-то, вам просто нужно разделить булку и ингредиенты (показывал ранее как это можно сделать) и вывести их. Не нужно придумывать дополнительные функции по рандому и т.п. сейчас это не требуется. Просто выводите как есть и всё.

```js
const { bun, ingredients } = useMemo(() => {
  return {
    bun: data.find(item => item.type === 'bun'),
    ingredients: data.filter(item => item.type !== 'bun'),
  };
}, [data]);

// ...

<ConstructorElement
    type="top"
    isLocked={true}
    text={`${bun.name} (верх)`}
    price={bun.price}
    thumbnail={bun.image}
    extraClass={styles.bunTopAndBottom}
  />
  
  {ingredients.map(...)}
```

2023-08-09 12:36 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

### **Работа принята, удачи в дальнейшем обучении.**

2023-08-10 16:28 UTC, merged